// GENERATED by scripts/build-brand-assets.py - do not edit by hand.
//
// The rendered size of the brand artwork, measured from the files that
// were actually written. Components lay these out with an explicit width
// and height, so a ratio that disagrees with the file stretches the
// artwork; taking it from here is the only way the two cannot drift.

export const BRAND_ASSET_SIZES = {
  mark: { width: 512, height: 512 },
  wordmark: { width: 720, height: 461 },
  loaderMark: { width: 192, height: 192 },
} as const;

export const BRAND_ASPECT = {
  mark: 512 / 512,
  wordmark: 720 / 461,
  loaderMark: 192 / 192,
} as const;
